language: node_js
node_js:
  - '7'
  - '6'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - yarn test
after_success:
  - yarn coverage:lcov
  - yarn codecov
  - yarn coveralls
cache: yarn
deploy:
  provider: npm
  email: ahmadbamieh@gmail.com
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    branch: master
